#!/usr/bin/env bash
# superst numbers
c=1
while [ $c -le 20 ]
do 
case $c in
4)
echo "4"
echo "bad luck from China"
;;
9)
echo "9"
echo "bad luck from Japan"
;;
17)
echo "17"
echo "bad luck from Italy"
;;
esac
((c++))
done

