#!/usr/bin/env bash
#!/bin/bash

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
handle_sigquit() {
    rm -f /var/run/myscript.pid
    exit 0
}

# Set trap for SIGTERM, SIGINT, and SIGQUIT signals
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Display "To infinity and beyond" indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done
